name: Build & Validate docs.html

on:
  push:
  pull_request:

jobs:
  build-validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install deps (optional)
        run: |
          python3 -m pip install --upgrade pip || true
          # bleach is optional; only needed if you pass --sanitize to generator
          python3 -m pip install bleach || true
      - name: Generate docs.html from docs/
        run: |
          python3 generate_docs.py --input-dir docs --template docs.html --output docs.html
      - name: Validate embedded JSON in docs.html
        run: |
          python3 scripts/validate.py
